# Generated by Django 3.1.6 on 2021-02-03 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 19, 51, 41, 78306, tzinfo=utc)),
        ),
    ]
